name: Test and publish packages

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: brainglobe/actions/lint@v1

  test:
    needs: linting
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Run all supported Python versions on linux
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest]
        # Include one windows and macos run
        include:
        - os: macos-latest
          python-version: "3.9"
        - os: windows-latest
          python-version: "3.9"
    steps:
      - uses: brainglobe/actions/test@v1
        with:
          python-version: ${{ matrix.python-version }}

  build_sdist:
    name: Build source distribution
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: brainglobe/actions/build_sdist@v1

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
    steps:
    - uses: brainglobe/actions/build_wheels@v1

  upload_all:
    name: Publish build distributions
    needs: [build_sdist, build_wheels]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_type == 'tag'
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist
    - uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.TWINE_API_KEY }}
